version: '3.8'

services:
  db:
    image: postgres
    volumes: 
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  pg_admin:
    image: dpage/pgadmin4
    ports:
      - "1500:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@email.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - ./db_admin:/var/lib/pgadmin4